Feat/pd 3081
pie-framework/pie-player-components pull request #137
Opened 2023-09-20 09:36 UTC by arimieandreea

2023-09-20 10:40 UTC, PatriciaRomaniuc approved these changes

2023-09-20 11:53 UTC, andreeapescar requested changes

2023-09-20 11:53 UTC, andreeapescar commented on src/components.d.ts
> +    'allowedResize': boolean;
make it optional

2023-09-20 11:53 UTC, andreeapescar commented on src/components.d.ts
> +    'allowedResize'?: boolean;
add comment

2023-09-20 11:53 UTC, andreeapescar commented on src/components/pie-player/pie-player.tsx
> +  @Prop() allowedResize: boolean = false;
add comment

2023-09-20 11:53 UTC, andreeapescar commented on src/components/pie-stimulus-layout/pie-stimulus-layout.tsx
> +  @State() isResizing = false;
add comment (what are these used for)

2023-09-20 11:53 UTC, andreeapescar commented on src/components/pie-stimulus-layout/pie-stimulus-layout.tsx
> +        <div id="stimulus"
if we'd define the style above and make it {} if allowedResize is false, would it work?

2023-09-21 07:37 UTC, andreeapescar commented
I have few comments on this:
1. All your commits have "chore: ...". The commit message type "chore" is typically used to indicate routine or administrative tasks that do not introduce new features, fix bugs, or make significant changes. In your case, you added a feature.
2. Please create a specific demo page for this new feature.
3. Check the issues I mentioned in the video I've sent you:
a. Resize bar not visible - I would also add some padding/margin/any spacing you're thinking
b. Weird behaviour on resizing when content is larger

2023-09-21 11:11 UTC, merged

2023-09-21 11:14 UTC, iacoshoria commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@pie-framework/pie-player-components/v/2.1.0)
- [GitHub release](https://github.com/pie-framework/pie-player-components/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: