Feat/pd 3082
pie-framework/pie-player-components pull request #140
Opened 2023-10-20 11:22 UTC by arimieandreea

2023-10-20 11:28 UTC, arimieandreea commented
https://illuminate.atlassian.net/jira/software/c/projects/PD/issues/PD-3082

2023-10-20 11:30 UTC, arimieandreea commented
I will leave a screen recording here in order to be clear. After the code review, we need to merge it and update version in api-components as well as in api browser.

2023-10-23 08:38 UTC, andreeapescar requested changes
Please change commits with respect to semantic-release commit format.

2023-10-23 08:38 UTC, andreeapescar commented on src/components/pie-stimulus-layout/pie-stimulus-layout.tsx
> +    this.readMoreButton.addEventListener("click", () => {
Can you please create a function for the event handler instead of having everything here?

2023-10-23 08:38 UTC, andreeapescar commented on src/demo/stimulus-item-narrow-width.html
> +    "pie": {
Nice work with demo page! :)

2023-10-23 13:06 UTC, andreeimiron approved these changes

2023-10-23 14:29 UTC, merged

2023-10-23 14:33 UTC, iacoshoria commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@pie-framework/pie-player-components/v/2.2.0)
- [GitHub release](https://github.com/pie-framework/pie-player-components/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: